<?php

$odp =[
    "Afghanistan"=>"Afganistan",
    "Bangladesh"=>"Bangladesz",
    "Argentina"=>"Argentyna",
    "Azerbaijan"=>"Azerbejdżan",
    "Bahamas"=>"Bahamy",
    "Bangladesh"=>"Bangladesz",
    "Belgium"=>"Belgia",
    "Brunei Darussalam"=>"Brunei",
    "Belarus"=>"Białoruś",
    "Belgium"=>"Belgia",
    "Bolivia"=>"Boliwia",
    "Bosnia and Herzegovina"=>"Bośnia i Hercegowina",
    "Brazil"=>"Brazylia",
    "Bulgaria"=>"Bułgaria",
    "Cambodia"=>"Kambodża",
    "Central African Republic"=>"Republika Środkowoafrykańska",
    "Democratic Republic of Congo"=>"Demokratyczna Republika Konga",
    "Canada"=>"Kanada",
    "Ivory Coast"=>"Wybrzeże Kości Słoniowej",
    "Czad"=>"Czad",
    "China"=>"Chiny",
    "Cuba"=>"Kuba",
    "Croatia"=>"Chorwacja",
    "Congo"=>"Kongo",
    "Cameroon"=>"Kamerun",
    "Costa Rica"=>"Kostaryka",
    "Cyprus"=>"Cypr",
    "Colombia"=>"Kolumbia",
    "Czechia"=>"Czechy",
    "Denmark"=>"Dania",
    "Djibouti"=>"Dżibuti",
    "Dominican Republic"=>"Republika Dominikany",
    "Ecuador"=>"Ekwador",
    "Egypt"=>"Egipt",
    "Equatorial Guinea"=>"Gwinea Równikowa",
    "Eritrea"=>"Erytrea",
    "Ethiopia"=>"Etiopia",
    "Falkland Islands"=>"Falklandy",
    "Fiji"=>"Fidżi",
    "Finland"=>"Finlandia",
    "France"=>"Francja",
    "French Guiana"=>"Gujana Francuska",
    "French Southern Territories"=>"Francuskie Terytoria Południowe",
    "Georgia"=>"Gruzja",
    "Germany"=>"Niemcy",
    "Greece"=>"Grecja",
    "Greenland"=>"Grenlandia",
    "Guatemala"=>"Gwatemala",
    "Guinea"=>"Gwinea",
    "Guyana"=>"Gujana",
    "Hungary"=>"Węgry",
    "Iceland"=>"Islandia",
    "India"=>"Indie",
    "Indonesia"=>"Indonezja",
    "Iraq"=>"Irak",
    "Ireland"=>"Irlandia",
    "Israel"=>"Izrael",
    "Italy"=>"Włochy",
    "Jamaica"=>"Jamajka",
    "Japan"=>"Japonia",
    "Jordan"=>"Jordania",
    "Kazakhstan"=>"Kazachstan",
    "Kenya"=>"Kenia",
    "South Korea"=>"Korea Południowa",
    "Kuwait"=>"Kuwejt",
    "Kyrgyzstan"=>"Kirgistan",
    "Latvia"=>"Łotwa",
    "Lebanon"=>"Liban",
    "Libya"=>"Libia",
    "Lithuania"=>"Litwa",
    "Luxembourg"=>"Luksemburg",
    "Madagascar"=>"Madagaskar",
    "Malaysia"=>"Malezja",
    "Mauritania"=>"Mauretania",
    "Mexico"=>"Meksyk",
    "Moldova"=>"Mołdawia",
    "Montenegro"=>"Czarnogóra",
    "Morocco"=>"Maroko",
    "Mozambique"=>"Mozambik",
    "Netherlands"=>"Holandia",
    "New Caledonia"=>"Nowa Kaledonia",
    "New Zealand"=>"Nowa Zelandia",
    "Nicaragua"=>"Nikaragua",
    "Norway"=>"Norwegia",
    "Palestine"=>"Palestyna",
    "Papua New Guinea"=>"Papua Nowa Gwinea",
    "Paraguay"=>"Paragwaj",
    "Philippines"=>"Filipiny",
    "Poland"=>"Polska",
    "Portugal"=>"Portugalia",
    "Puerto Rico"=>"Portoryko",
    "Qatar"=>"Katar",
    "Republic of Kosovo"=>"Republika Kosowa",
    "Romania"=>"Rumunia",
    "Saudi Arabia"=>"Arabia Saudyjska",
    "Slovakia"=>"Słowacja",
    "Slovenia"=>"Słowenia",
    "Solomon Islands"=>"Wyspy Salomona",
    "South Africa"=>"Afryka Południowa",
    "South Sudan"=>"Południowy Sudan",
    "Spain"=>"Hiszpania",
    "Suriname"=>"Surinam",
    "Svalbard and Jan Mayen"=>"Svalbard i Jan Mayen",
    "Swaziland"=>"Suazi",
    "Sweden"=>"Szwecja",
    "Switzerland"=>"Szwajcaria",
    "Syrian Arab Republic"=>"Republika Syryjsko-Arabska",
    "Taiwan"=>"Tajwan",
    "Tajikistan"=>"Tadżykistan",
    "Thailand"=>"Tajlandia",
    "Timor-Leste"=>"Timor Wschodni",
    "Trinidad and Tobago"=>"Trynidad i Tobago",
    "Tunisia"=>"Tunezja",
    "Turkey"=>"Turcja",
    "Turkmenistan"=>"Turkmenia",
    "Ukraine"=>"Ukraina",
    "United Kingdom"=>"Wielka Brytania",
    "Uruguay"=>"Urugwaj",
    "Venezuela"=>"Wenezuela",
    "Western Sahara"=>"Sahara Zachodnia",
    "Yemen"=>"Jemen",
    "Singapore"=>"Singapur",
    "Kosovo"=>"Kosowo",
    "DR Congo"=>"DR Konga",
    "North Korea"=>"Korea Północna",
    "Russia"=>"Rosja",
    "UAE"=>"Zjednoczone Emiraty Arabskie",
    "Vietnam"=>"Wietnam"
];
if (isset($_POST["dane"])){
    $arr =$_POST["dane"];
    $arr = json_decode($arr);
    for ($i=1; $i<=181; $i++){
        $arr[$i] =  get_object_vars($arr[$i]);
        if (isset($odp[$arr[$i]["title"]])){
            $arr[$i]["title"] = $odp[$arr[$i]["title"]];
        }
    }
    echo json_encode($arr);
    }



?>
